version: '3.8'

services:
  vnc-manager:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  # Ejemplo de servicio adicional (Opcional)
  # nginx-proxy:
  #   image: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
